[package]
versioned_files = ["Cargo.toml"]
changelog = "CHANGELOG.md"

[github]
owner = "purnamahesh"
repo = "expense-tracker"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"