name: Audit
on:
  workflow_dispatch:
  workflow_call:
#   pull_request:

# permissions:
#   contents: write       # Trigger workflows on PR branch
#   actions: write        # Dispatch workflows
#   pull-requests: write  # Comment on PRs and react to comments
#   id-token: write       # OIDC for Artifactory (if workflows need it)
#   packages: write       # Docker operations (if building images)


jobs:
  dispatch:
    uses: purnamahesh/reusable-workflows/.github/workflows/rust-audit.yaml@feature/rust-ci
    secrets: inherit
