name: Pre-Release
on:
  workflow_dispatch:
    inputs:
      pre-release-label:
        default: 'alpha'

jobs:
  pre-release:
    uses: purnamahesh/reusable-workflows/.github/workflows/rust-pre-release.yaml@feature/rust-ci
    with:
      pre-release-label: ${{ inputs.pre-release-label }}
    secrets: inherit
      # PAT: ${{ secrets.PAT }}
      # CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
